"""
Digital Twin API
Secure endpoints for reading and refreshing the patient's Digital Twin state.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.api.deps import get_current_user
from app.db.models import DigitalTwin, Patient, TwinPrediction, User
from app.db.session import get_db
from app.services.digital_twin import generate_twin_state

router = APIRouter()


@router.get("/patient/{patient_id}")
async def get_digital_twin(
    patient_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Returns the patient's Digital Twin health scores."""
    pat_res = await db.execute(select(Patient).where(Patient.patient_id == patient_id, Patient.owner_id == current_user.id))
    if not pat_res.scalars().first():
        raise HTTPException(status_code=404, detail="Patient not found or unauthorized")

    res = await db.execute(select(DigitalTwin).where(DigitalTwin.patient_id == patient_id))
    twin = res.scalars().first()

    if not twin:
        await generate_twin_state(patient_id, db)
        res = await db.execute(select(DigitalTwin).where(DigitalTwin.patient_id == patient_id))
        twin = res.scalars().first()

    if not twin:
        return {"health_score": 100, "overall_status": "Optimal", "message": "No data yet. Upload reports to generate twin."}

    return twin


@router.get("/patient/{patient_id}/predictions")
async def get_twin_predictions(
    patient_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Returns the metric projections generated by the Digital Twin."""
    pat_res = await db.execute(select(Patient).where(Patient.patient_id == patient_id, Patient.owner_id == current_user.id))
    if not pat_res.scalars().first():
        raise HTTPException(status_code=404, detail="Patient not found or unauthorized")

    res = await db.execute(select(TwinPrediction).where(TwinPrediction.patient_id == patient_id))
    return res.scalars().all()


@router.post("/patient/{patient_id}/refresh")
async def refresh_twin_state(
    patient_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Triggers a full recalculation of the Digital Twin state from current DB data."""
    pat_res = await db.execute(select(Patient).where(Patient.patient_id == patient_id, Patient.owner_id == current_user.id))
    if not pat_res.scalars().first():
        raise HTTPException(status_code=404, detail="Patient not found or unauthorized")

    scores = await generate_twin_state(patient_id, db)
    return {"message": "Digital Twin state refreshed successfully", "scores": scores}


@router.get("/patient/{patient_id}/fusion")
async def get_data_fusion(
    patient_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Returns aggregated lab panels and synthesized insights for Data Fusion Center."""
    from app.db.models import HealthMetric
    
    pat_res = await db.execute(select(Patient).where(Patient.patient_id == patient_id, Patient.owner_id == current_user.id))
    if not pat_res.scalars().first():
        raise HTTPException(status_code=404, detail="Patient not found or unauthorized")

    # Fetch latest metrics
    metrics_res = await db.execute(select(HealthMetric).where(HealthMetric.patient_id == patient_id).order_by(HealthMetric.recorded_at.asc()))
    metrics = metrics_res.scalars().all()
    
    # Get latest value per metric
    latest_metrics = {}
    for m in metrics:
        if m.value is not None:
            latest_metrics[m.metric_name.lower().replace(" ", "_")] = {
                "value": f"{m.value} {m.unit or ''}".strip(),
                "status": m.status or "Normal",
                "raw_val": m.value,
                "name": m.metric_name
            }

    # Group into panels
    panels = []
    
    cbc_data = {}
    if "white_blood_cells" in latest_metrics: cbc_data["WBC"] = latest_metrics["white_blood_cells"]["value"]
    if "hemoglobin" in latest_metrics: cbc_data["Hb"] = latest_metrics["hemoglobin"]["value"]
    if "platelets" in latest_metrics: cbc_data["Plt"] = latest_metrics["platelets"]["value"]
    
    if cbc_data:
        panels.append({"id": "cbc", "label": "CBC Profile", "color": "text-red-500", "bg": "bg-red-100", "data": cbc_data})
        
    lipid_data = {}
    if "cholesterol" in latest_metrics or "cholesterol_total" in latest_metrics:
        val = latest_metrics.get("cholesterol_total", latest_metrics.get("cholesterol", {}))
        if val: lipid_data["Total Chol"] = val["value"]
    if "ldl" in latest_metrics or "ldl_cholesterol" in latest_metrics:
        val = latest_metrics.get("ldl_cholesterol", latest_metrics.get("ldl", {}))
        if val: lipid_data["LDL"] = val["value"]
    if "hdl" in latest_metrics or "hdl_cholesterol" in latest_metrics:
        val = latest_metrics.get("hdl_cholesterol", latest_metrics.get("hdl", {}))
        if val: lipid_data["HDL"] = val["value"]
        
    if lipid_data:
        panels.append({"id": "lipid", "label": "Lipid Profile", "color": "text-amber-500", "bg": "bg-amber-100", "data": lipid_data})
        
    metabolic_data = {}
    if "hba1c" in latest_metrics: metabolic_data["HbA1c"] = latest_metrics["hba1c"]["value"]
    if "fasting_glucose" in latest_metrics: metabolic_data["Glucose"] = latest_metrics["fasting_glucose"]["value"]
    
    if metabolic_data:
        panels.append({"id": "metabolic", "label": "Metabolic Panel", "color": "text-blue-500", "bg": "bg-blue-100", "data": metabolic_data})
        
    renal_data = {}
    if "creatinine" in latest_metrics: renal_data["Creatinine"] = latest_metrics["creatinine"]["value"]
    if "egfr" in latest_metrics: renal_data["eGFR"] = latest_metrics["egfr"]["value"]
    
    if renal_data:
        panels.append({"id": "renal", "label": "Renal Function", "color": "text-emerald-500", "bg": "bg-emerald-100", "data": renal_data})

    # Generate heuristic insights
    insights = []
    
    has_high_ldl = latest_metrics.get("ldl", {}).get("raw_val", 0) > 130 or latest_metrics.get("ldl_cholesterol", {}).get("raw_val", 0) > 130
    has_high_glucose = latest_metrics.get("hba1c", {}).get("raw_val", 0) > 5.7 or latest_metrics.get("fasting_glucose", {}).get("raw_val", 0) > 100
    
    if has_high_ldl and has_high_glucose:
        insights.append({
            "type": "warning",
            "title": "Compound Cardiovascular & Metabolic Risk",
            "description": f"AI identified a strong correlation between elevated LDL ({latest_metrics.get('ldl', latest_metrics.get('ldl_cholesterol', {})).get('value', 'High')}) and abnormal metabolic markers (HbA1c/Glucose). This combination significantly increases the risk of metabolic syndrome and cardiovascular events."
        })
    elif has_high_glucose:
        insights.append({
            "type": "warning",
            "title": "Metabolic Stress Detected",
            "description": f"Elevated glycemic markers (HbA1c {latest_metrics.get('hba1c', {}).get('value', 'N/A')}) indicate early insulin resistance."
        })
    elif has_high_ldl:
        insights.append({
            "type": "warning",
            "title": "Atherogenic Lipid Profile",
            "description": "Elevated LDL cholesterol increases risk of plaque formation. Recommend lifestyle intervention."
        })
        
    if "white_blood_cells" in latest_metrics and "hemoglobin" in latest_metrics:
        wbc = latest_metrics["white_blood_cells"]["raw_val"]
        if wbc >= 4 and wbc <= 11:
            insights.append({
                "type": "success",
                "title": "Hematological Stability",
                "description": f"CBC indicators show no active systemic inflammation (WBC normal at {latest_metrics['white_blood_cells']['value']}). Good oxygen transport capacity."
            })
            
    # Default insight if nothing triggered but data exists
    if not insights and latest_metrics:
        insights.append({
            "type": "success",
            "title": "Biomarker Stability",
            "description": "All synthesized lab streams are within optimal or acceptable reference ranges. No immediate compound risks identified."
        })

    # Action plan heuristics
    action_plan = []
    if has_high_glucose:
        action_plan.append("Implement low-glycemic index diet and review in 90 days.")
    if has_high_ldl:
        action_plan.append("Consider starting statin therapy or structured cardiovascular exercise routine.")
    if not action_plan:
        action_plan.append("Maintain current lifestyle and attend scheduled follow-ups.")
        
    return {
        "panels": panels,
        "insights": insights,
        "action_plan": action_plan,
        "has_data": len(panels) > 0
    }
